# Generated by Django 4.1.6 on 2023-02-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
