# Generated by Django 4.1.6 on 2023-02-23 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_medicine_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine', to='pharmacy.prescription'),
        ),
    ]
