# Generated by Django 4.1.6 on 2023-02-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_appointmenttime_alter_appointment_day_timesfortheday_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesfortheday',
            name='Doctor',
        ),
        migrations.RemoveField(
            model_name='timesfortheday',
            name='times',
        ),
        migrations.DeleteModel(
            name='AppointmentTime',
        ),
        migrations.DeleteModel(
            name='TimesForTheDay',
        ),
    ]
