# Generated by Django 4.1.6 on 2023-02-13 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_reception_doctor_address_alter_doctor_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reception',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
        migrations.DeleteModel(
            name='Reception',
        ),
    ]
