# Generated by Django 4.1.6 on 2023-02-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_timesfortheday_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_status',
            field=models.CharField(choices=[('ACP', 'accepted'), ('DEC', 'declined')], default='DEC', max_length=60),
        ),
        migrations.AlterField(
            model_name='doctorcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
