# Generated by Django 4.1.6 on 2023-02-19 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_patient_requested_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesfortheday',
            name='day',
            field=models.DateField(default=datetime.date(2023, 2, 19)),
        ),
    ]
