# Generated by Django 4.1.6 on 2023-02-24 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='accounts.insurance'),
        ),
    ]
