# Generated by Django 4.1.6 on 2023-02-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_doctor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'patient', 'verbose_name_plural': 'patients'},
        ),
    ]
