# Generated by Django 4.1.6 on 2023-02-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_patient_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='requested_department',
            field=models.CharField(choices=[('General', 'General'), ('Cardiologist', 'Cardiologist'), ('Dermatologists', 'Dermatologists'), ('Emergency Medicine Specialists', 'Emergency Medicine Specialists'), ('Allergists/Immunologists', 'Allergists/Immunologists'), ('Anesthesiologists', 'Anesthesiologists'), ('Colon and Rectal Surgeons', 'Colon and Rectal Surgeons')], default='General', max_length=40),
        ),
    ]
