# Generated by Django 4.1.6 on 2023-02-17 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_doctor_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='times',
        ),
        migrations.CreateModel(
            name='TimesForTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.CharField(choices=[('9', '9'), ('9:30', '9:30'), ('10', '10'), ('10:30', '10:30'), ('11', '11'), ('11:30', '11:30'), ('12', '12'), ('12:30', '12:30')], default='9', max_length=30)),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='accounts.doctor')),
            ],
        ),
    ]
