# Generated by Django 4.1.6 on 2023-02-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_doctor_times_timesfortheday'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesfortheday',
            name='day',
            field=models.DateField(default='2023-02-17'),
        ),
    ]
