# Generated by Django 4.1.6 on 2023-02-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_timesfortheday_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesfortheday',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
