# Generated by Django 4.1.6 on 2023-02-18 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_timesfortheday_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesfortheday',
            name='day',
            field=models.DateField(default=datetime.date(2023, 2, 18)),
        ),
    ]
