# Generated by Django 4.1.6 on 2023-02-18 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_time', models.CharField(choices=[('9', '9'), ('9:30', '9:30'), ('10', '10'), ('10:30', '10:30'), ('11', '11'), ('11:30', '11:30'), ('12', '12'), ('12:30', '12:30')], max_length=40)),
                ('day', models.DateField(default=datetime.date(2023, 2, 18))),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
