# Generated by Django 4.1.6 on 2023-02-21 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date(2023, 2, 21))),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('DEC', 'declined'), ('ACP', 'accepted'), ('DON', 'done'), ('DO', 'doing'), ('QUE', 'in-queue')], default='QUE', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('appointment_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='accounts.appointmenttime')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='accounts.patient')),
            ],
        ),
    ]
