# Generated by Django 4.1.6 on 2023-02-22 06:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.date(2023, 2, 22)),
        ),
        migrations.CreateModel(
            name='TimesForTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date(2023, 2, 22))),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_for_day', to='accounts.doctor')),
                ('times', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_for_day', to='Hospital.appointmenttime')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='Hospital.appointmenttime'),
        ),
    ]
