# Generated by Django 4.1.6 on 2023-02-23 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_appointmenttime_alter_appointment_day_timesfortheday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(default=datetime.date(2023, 2, 23)),
        ),
        migrations.AlterField(
            model_name='timesfortheday',
            name='day',
            field=models.DateField(default=datetime.date(2023, 2, 23)),
        ),
    ]
