# Generated by Django 4.1.6 on 2023-02-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_rename_appointments_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reception',
        ),
    ]
