# Generated by Django 4.1.6 on 2023-02-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_alter_appointment_day_prescription_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
