# Generated by Django 4.1.6 on 2023-02-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0005_alter_appointment_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.DateField(default='2023-02-17'),
        ),
    ]
