# Generated by Django 4.1.6 on 2023-02-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_remove_appointment_time_appointment_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
